### ISSUE TITLE
No way to load rundeck plugins 

### ISSUE THREAD

**Issue by adragoset** [hbjcr/rundeck#2]
Currently no way to load rundeck plugins. I extended from this container created a startup script to copy plugins from a mount into /etc/rundeck/libext but you may want to incorporate plugin copying functionality into this container by allowing the user to mount a directory and specify the plugin directory to copy plugins from with an env variable.

**Comment by hbjcr** [comment]
Currently, the $RDECK_BASE folder is [being mapped](https://github.com/hbjcr/rundeck/blob/master/Dockerfile) to a volume:

VOLUME  [ "$RDECK_BASE", "/var/lib/rundeck/.ssh", "$RDECK_BASE/server/logs" ]

The [official documentation](http://rundeck.org/docs/plugins-user-guide/installing.html) also indicates (as you explained) that plugins must be copied into the $RDECK_BASE/libext folder

So basically, you should be able to copy the plugins into the $RDECK_BASE mapped folder in your host, or you can manually map it into a local folder in your host were your plugins would reside. Would that solve your issue?

**Comment by hbjcr** [comment]
Feel free to reopen if the solution proposed doesn't fix your issue.
